services:
  - type: web
    name: voice-tts-app
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app
    envVars:
      - key: API_KEY
        sync: false  # Set this manually in the Render dashboard
      - key: VOICE_ID
        sync: false  # Set this manually in the Render dashboard
